---
version: '3'
services:
  mongo0:
    network_mode: host
    image: percona/percona-server-mongodb:${TEST_PSMDB_VERSION:-latest}
    command: --port=${TEST_PRIMARY_PORT:-65217}
    volumes:
      - ./docker/test/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/test/mongod.key:/mongod.key:ro
      - ./docker/test/ssl/rootCA.crt:/rootCA.crt:ro
      - ./docker/test/ssl/mongodb.pem:/mongod.pem:ro
  mongo1:
    network_mode: host
    image: percona/percona-server-mongodb:${TEST_PSMDB_VERSION:-latest}
    command: --port=${TEST_SECONDARY1_PORT:-65218}
    volumes:
      - ./docker/test/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/test/mongod.key:/mongod.key:ro
      - ./docker/test/ssl/rootCA.crt:/rootCA.crt:ro
      - ./docker/test/ssl/mongodb.pem:/mongod.pem:ro
  mongo2:
    network_mode: host
    image: percona/percona-server-mongodb:${TEST_PSMDB_VERSION:-latest}
    command: --port=${TEST_SECONDARY2_PORT:-65219}
    volumes:
      - ./docker/test/entrypoint.sh:/entrypoint.sh:ro
      - ./docker/test/mongod.key:/mongod.key:ro
      - ./docker/test/ssl/rootCA.crt:/rootCA.crt:ro
      - ./docker/test/ssl/mongodb.pem:/mongod.pem:ro
  init:
    network_mode: host
    image: percona/percona-server-mongodb:${TEST_PSMDB_VERSION:-latest}
    environment:
      - TEST_ADMIN_USER=${TEST_ADMIN_USER:-admin}
      - TEST_ADMIN_PASSWORD=${TEST_ADMIN_PASSWORD:-123456}
      - TEST_RS_NAME=${TEST_RS_NAME:-rs}
      - TEST_PRIMARY_PORT=${TEST_PRIMARY_PORT:-65217}
      - TEST_SECONDARY1_PORT=${TEST_SECONDARY1_PORT:-65218}
      - TEST_SECONDARY2_PORT=${TEST_SECONDARY2_PORT:-65219}
    volumes:
      - ./docker/test/init-test-replset.sh:/entrypoint.sh:ro
      - ./docker/test/ssl/rootCA.crt:/rootCA.crt:ro
      - ./docker/test/ssl/client.pem:/client.pem:ro
    depends_on:
      - mongo0
      - mongo1
      - mongo2
