ARG GOLANG_DOCKERHUB_TAG
FROM golang:$GOLANG_DOCKERHUB_TAG as builder

WORKDIR /mongodb-tools

COPY . .

RUN make bin/mongodb-healthcheck

# Run stage
FROM scratch

COPY --from=builder /mongodb-tools/bin/mongodb-healthcheck /mongodb-healthcheck

ENTRYPOINT ["/mongodb-healthcheck"]
