ARG GOLANG_DOCKERHUB_TAG

FROM golang:$GOLANG_DOCKERHUB_TAG

WORKDIR /go/src/github.com/vtomasr5/mongodb-tools
COPY . .

RUN apt-get update && \
    apt-get install -y zip && \
    apt-get clean all

CMD make k8s
    #make test-full && \
    #&& \
    #upx bin/*
